### ISSUE TITLE
Add more images of app to README.md

### ISSUE THREAD

**Issue by TaQuangKhoi** [sonnguyen16/ionic-vue-app#1]
@sonnguyen16 Chào ông,

Thêm vài hình ảnh vào README.md cho mọi người thấy giao diện nó đẹp thế nào đi chứ.

**Comment by sonnguyen16** [comment]
đã update, cơ mà ảnh load hơi lâu :))

**Comment by TaQuangKhoi** [comment]
@sonnguyen16 Bên tui load trong 1 giây, chắc do mạng ông chậm ấy.
